# Generated by Django 5.0 on 2023-12-24 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='Account/profile_images/default.jpg', null=True, upload_to='Account/profile_images', verbose_name='Profile Picture')),
                ('cover_pic', models.ImageField(blank=True, default='Account/cover_images/_default.jpg', null=True, upload_to='Account/cover_images', verbose_name='Cover Picture')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True)),
                ('headline', models.CharField(blank=True, max_length=80, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('remote_fol_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote Folder ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
