# Generated by Django 5.2 on 2025-05-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_cover_pic_profile_cover_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
