services:
  django_app:
    build: .
    volumes:
      - .:/app           # Mount the application code
      - static_volume:/app/static  # Mount a named volume to /app/static for the static files
    expose:
      - "8000"  # Expose the app internally to Nginx (only accessible from within the Docker network)
    environment:
      - DJANGO_ENV=production

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs  # Mount SSL certs
      - static_volume:/static  # Mount the named volume to /static for Nginx to serve
    ports:
      - "443:443"  # Expose Nginx to the host
    depends_on:
      - django_app

volumes:
  static_volume:  # Define a named volume for static files
