
services:
  django_app:
    build: .
    volumes:
      - .:/app
      - ./static:/static
    expose:
      - "8000"  # Expose the app internally to Nginx (only accessible from within the Docker network)

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs  # Mount SSL certs
      - ./static:/static            # Mount static files
    ports:
      - "443:443"  # Expose Nginx to the host
    depends_on:
      - django_app

