# Generated by Django 5.0.2 on 2024-03-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_globalannouncement_alter_home_latestupdates_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalannouncement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Global notifications'},
        ),
        migrations.AlterModelOptions(
            name='home_importantlinks',
            options={'verbose_name': 'link', 'verbose_name_plural': 'Important links'},
        ),
        migrations.AlterModelOptions(
            name='home_latestupdates',
            options={'verbose_name': 'update', 'verbose_name_plural': 'User specific updates'},
        ),
        migrations.AlterModelOptions(
            name='image_gallery',
            options={'verbose_name': 'image', 'verbose_name_plural': 'Image gallery'},
        ),
        migrations.AlterModelOptions(
            name='urltogdrive',
            options={'verbose_name': 'file', 'verbose_name_plural': 'Cloud files'},
        ),
    ]
