# Generated by Django 5.1.4 on 2024-12-29 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_home_latestupdates_latestupdates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='globalannouncement',
            index=models.Index(fields=['is_active', 'created_at'], name='main_global_is_acti_200f60_idx'),
        ),
        migrations.AddIndex(
            model_name='latestupdates',
            index=models.Index(fields=['user', 'created_at'], name='main_latest_user_id_05880f_idx'),
        ),
    ]
